### ISSUE TITLE
New version broken, example does not work anymore

### ISSUE THREAD

**Issue by HriBB** [nashvail/ReactPathMenu#6]
First of all thanks for this great component. I'm using the old version in my app and it works perfectly.

I tried to upgrade to the new version which uses `react-motion@0.4+`, but it does not work as expected. The expand animation is OK, but collapse does not work properly, small buttons are not collapsed in the right sequence.

Also the [example](https://rawgit.com/nashvail/ReactPathMenu/staggered-motion/public/index.html) does not work anymore, there is an error

```
Warning: Failed prop type: Invalid prop `defaultStyles[0].top` of type `object` supplied to `StaggeredMotion`, expected `number`.
    in StaggeredMotion (created by APP)
    in APP
```

Just wanted to let you know. When I find some time, I will try to make it work with the latest version of `react-motion`.

**Comment by nashvail** [comment]
We had a PR @mathew3 for `react-motion@0.4+` support. (https://github.com/nashvail/ReactPathMenu/pull/5) Everything seemed to work fine. Looks like we'll have to take another look.

**Comment by jepser** [comment]
It has been more than a month, any updates?

**Comment by nashvail** [comment]
@jepser The demos have been updated and working. Waiting for your green flag to close this issue
